# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled 0xABDOU DZB e.g., [user1, user2]
patreon: # Replace with a single Patreon 0xABDOU DZB
open_collective: # Replace with a single Open Collective 0xABDOU DZB
ko_fi: # Replace with a single Ko-fi 0xABDOU DZB
tidelift: # Replace with a single Tidelift platform-0xABDOU DZB/package-0xABDOU DZB e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay 0xABDOU DZB
issuehunt: # Replace with a single IssueHunt 0xABDOU DZB
otechie: # Replace with a single Otechie 0xABDOU DZB
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-0xABDOU DZB e.g., cloud-foundry
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
